### ISSUE TITLE
JSON syntax not coloring keys more than 2 levels deep

### ISSUE THREAD

**Issue by blainsmith** [jesseweed/seti-syntax#103]
It seems that the coloring only applies to 2 levels of JSON keys and everything after that is just white.

![screen shot 2015-06-22 at 10 42 13 am](https://cloud.githubusercontent.com/assets/483829/8284683/2d3f3c5e-18cc-11e5-8872-4081a2d5549c.png)

**Comment by karloluis** [comment]
It seems to me that the syntax considers anything after the colon as a values. Making the syntax look ahead might be a bit too intensive. What version was this in?
