### ISSUE TITLE
js inline syntax improve, single 'quotes' vs "double" strings

### ISSUE THREAD

**Issue by arturparkhisenko** [jesseweed/seti-syntax#105]
I think we need highlight single quotes strings like a double quoted (inlined js):
![seti-syntax](https://cloud.githubusercontent.com/assets/139212/9625708/cc12a98e-5160-11e5-96e4-930de91e7e60.png)

```javascript
//github markdown highlight
var single = 'text', double = "text";
```

**Comment by marshmellow1328** [comment]
+1

**Comment by jesseweed** [comment]
Hmm, is that in a regular .js JavaScript file? This is how I see it in both .js and .coffee files: ![screenshot 2015-11-01 14 55 11](https://cloud.githubusercontent.com/assets/719964/10871298/9e4bd5b2-80a8-11e5-8c69-186de3690fb0.png)

Let me know if you have any steps to repro and I can see if I can figure out the issue.

**Comment by ikeagold** [comment]
@jesseweed yep, you're right, its an inlined js in *.html

**Comment by arturparkhisenko** [comment]
@jesseweed i don't see this problem in 1.0.1, thanks!
