### ISSUE TITLE
Cursor off

### ISSUE THREAD

**Issue by xenspidey** [jesseweed/seti-syntax#108]
The cursor position is not lining up with text. Switching syntax themes fixes it so it must be theme related

**Comment by thewalkingtoast** [comment]
Duplicate of #106.

**Comment by derekclair** [comment]
I don't think it's a duplicate, cause the proposed solution in #106 isn't solving it for me... The cursor matches the selector but it's still way off....

**Comment by Arcanemagus** [comment]
@derekclair did you restart Atom after making the fix? The solution in #106 is definitely the fix to this issue...

**Comment by derekclair** [comment]
And... we're back in business. Thank you @Arcanemagus!

**Comment by Arcanemagus** [comment]
Good to hear :wink:.

**Comment by jesseweed** [comment]
This is fixed in 0.4.1 which was just published to apm.
