### ISSUE TITLE
My index cursor is 1 digit after the text

### ISSUE THREAD

**Issue by opexa** [jesseweed/seti-syntax#109]
My index/blinking cursor in the text editor is broken.Its actually 1 digit after thing I've selected.How to fix it

**Comment by dab00** [comment]
Same here

**Comment by opexa** [comment]
GOD DAMN THANK YOU!GOD BLESS YA!

**Comment by msyrus** [comment]
The problem is due to introducing "Enable Shadow DOM" in Atom 1.1

**Comment by opexa** [comment]
Whats this "Shadow DOM"

**Comment by jesseweed** [comment]
This is fixed in 0.4.1 which is published to apm now.
