### ISSUE TITLE
Wrong syntax highlighting of js reserved words

### ISSUE THREAD

**Issue by OmgImAlexis** [jesseweed/seti-syntax#110]
Both `Image` and `async` are highlighted but as far as I know neither are reserved words so there should be no reason for that.

![screen shot 2015-11-02 at 3 43 00 pm](https://cloud.githubusercontent.com/assets/6525926/10874691/94c2ae5a-8178-11e5-8f5b-d84f2d21a32e.png)

**Comment by jesseweed** [comment]
Hey @OmgImAlexis, so the highlighting is actually defined by the [atom/language-javascript](https://github.com/atom/language-javascript/blob/master/grammars/javascript.cson) package, I just apply a styles based on the classes assigned by that package. 

According to the definitions file in that repo, `Image` gets the same class as `Array`, `Boolean`, `Date`, `Function`, etc.

And, while I didn't parse through all of the regex rules, as best as I can tell, `async` gets the same class applied as `var`, `this`, `constant`, `class`, etc.

I know there's actually a JS api for `Image`, don't remember on `async` off the top of my head.

Anyway, I will double check that everything is being applied appropriately on the Seti side, but I believe it is (the default atom themes all apply styles the same). I'd encourage you to file an issue on the [atom/language-javascript](https://github.com/atom/language-javascript/blob/master/grammars/javascript.cson) repo if you think it's incorrect.

Cheers!

**Comment by OmgImAlexis** [comment]
@jesseweed thanks for the quick reply. I'll definitely open an issue with them.
