### ISSUE TITLE
'return' keyword should have different color

### ISSUE THREAD

**Issue by aheshan** [jesseweed/seti-syntax#112]
Function 'return' keyword should have different color.

See attachment for reference.

![seti_syntax_return](https://cloud.githubusercontent.com/assets/4686815/11715060/cefe0704-9f64-11e5-8e97-b9ee40553f47.png)

**Comment by karloluis** [comment]
what was the file-type or language in which this issue was found? Also what version?

**Comment by aheshan** [comment]
I am using PHP language and file type was .php

**Comment by jesseweed** [comment]
I think this should be resolved in 1.0. Feel free to re-open if you still see a problem.
