### ISSUE TITLE
Colors messed up (no consistency)

### ISSUE THREAD

**Issue by danielbonnell** [jesseweed/seti-syntax#113]
Hi,

I've been using the Seti Syntax theme for over a year now and have been loving it. When I opened up Atom this morning though, I was surprised to find that the color palette is all screwed up. I code primarily in Javascript. Consider the following block of code in the attached image.

Up until this point, I could expect that `app.controller` on line 289 would be white, my dependencies (strings) would be blue, `function` would be yellow, and its arguments would be blue. Now `app.controller` is green.

Moving on to line 290, `$scope.current_page = photosAPI.current_page;` is all green, where before everything was white except for the `=` operator. 

![screen shot 2016-01-29 at 10 38 25 am](https://cloud.githubusercontent.com/assets/8513877/12679912/dd650734-c674-11e5-80f6-1da6275611f9.png)

I'm not sure if this is a bug with Seti Syntax or Atom, but in any case, it's really thrown me off.

**Comment by jesseweed** [comment]
Hmm, I haven't updated Seti in a few months, so it's most likely a change introduced in Atom recently, but I'll take a look.

**Comment by nwhite89** [comment]
:+1: yeah I noticed this also when I updated to Atom `1.4.0` :(

**Comment by sttracy4** [comment]
I am having the same issue after updating Atom

**Comment by jesseweed** [comment]
I think this should be resolved in 1.0. Feel free to re-open if you still see a problem.
