### ISSUE TITLE
how to customize background color in style.less?

### ISSUE THREAD

**Issue by dragonxlwang** [jesseweed/seti-syntax#119]
When changing the background color in style.less using selector atom-text-editor, the scroll bar's color (right-side of the picture, left of the minimap) remained unchanged. Is there a way to redefine that instead of touching seti-syntax directly?

![image](https://cloud.githubusercontent.com/assets/15812510/14051394/8a2d7fc2-f290-11e5-9bac-03e4fe0723bf.png)

**Comment by jesseweed** [comment]
Hi @dragonxlwang, have a look at this thread for details on how to style the scrollbar: https://discuss.atom.io/t/change-the-color-and-width-of-editors-sidebar/18545
