### ISSUE TITLE
Uninstall Seti Syntax Error + No Syntax Highlighting 

### ISSUE THREAD

**Issue by HaythmA** [jesseweed/seti-syntax#127]
Hi,

I am trying to uninstall Seti syntax but I keep getting this error:

<img width="870" alt="screen shot 2016-05-18 at 5 23 31 pm" src="https://cloud.githubusercontent.com/assets/11994129/15350536/5ab975e0-1d1d-11e6-9b37-8fb10993212c.png">

This is what Seti looks like on a python file:
<img width="563" alt="screen shot 2016-05-18 at 5 23 47 pm" src="https://cloud.githubusercontent.com/assets/11994129/15350535/5ab4f77c-1d1d-11e6-8c5f-f956b50fcedb.png">

Thank you.

**Comment by HeaTx** [comment]
Same error during the day, but when I restarted Atom, the package wasn't installed anymore (I needed that to reinstall).

**Comment by HaythmA** [comment]
That fixed it. Thank you.

**Comment by jesseweed** [comment]
I've been getting this error a lot lately anytime I uninstall a package. I think it's a general Atom bug (though haven't checked that it's filed).

**Comment by HeaTx** [comment]
yeah, here it is
https://github.com/atom/atom/issues/11464#issuecomment-219902806
