### ISSUE TITLE
Syntax highlighting not applied to code

### ISSUE THREAD

**Issue by Flujible** [jesseweed/seti-syntax#147]
Been using this theme for a while, but suddenly the highlighting just isn't being applied to my code (JS and Python). Ive tried re-installing many times, and have even deleted the .atom folder and reinstalled that way, but still not being applied even with the fresh atom install
![image](https://cloud.githubusercontent.com/assets/9479802/23270560/19ba9612-f9ec-11e6-9179-227f7c7d1fa1.png)

**Comment by charlesj** [comment]
Looks like this might have a duplicate in https://github.com/jesseweed/seti-syntax/issues/149

I'm having the same issue on Ubuntu, and I've not been able to figure out a workaround yet.

**Comment by Flujible** [comment]
Yeah it looks like the same issue, I found a workaround a posted it in #149, hope it helps!
