### ISSUE TITLE
Match case letters not visible when selected

### ISSUE THREAD

**Issue by MaybeRex** [jesseweed/seti-syntax#152]
# Issue 
When searching and match case is selected the letters are not visible 

# Info

Using the blue theme 

![screen shot 2017-05-15 at 7 59 23 am](https://cloud.githubusercontent.com/assets/13438003/26063986/7a202b7e-3944-11e7-9069-8f662101b5e5.png)
![screen shot 2017-05-15 at 7 59 33 am](https://cloud.githubusercontent.com/assets/13438003/26063987/7bf4fe16-3944-11e7-9d03-3164c3603189.png)

**Comment by Alhadis** [comment]
Wrong repo, but I submitted a fix for this [over here](https://github.com/jesseweed/seti-ui/pull/447). =)
