### ISSUE TITLE
Wrong syntax higlighting parenthesis (C++)

### ISSUE THREAD

**Issue by Shammah** [jesseweed/seti-syntax#3]
I opened up an issue with the C++ language guys, but according to them it's an issue with the theme and not the parser: https://github.com/atom/language-c/issues/30#issuecomment-47979032

Original:

The syntax highlighting of parenthesis in function calls does not work properly, as demonstrated in the image below.

http://imgur.com/KfDzDrj
![image](https://cloud.githubusercontent.com/assets/1854439/3474962/cb024376-02ea-11e4-966d-c99b608fdeaa.png)

**Comment by jzhu98** [comment]
I managed to track down the exact problem. I've submitted a pull request to the language-c repo here:
https://github.com/atom/language-c/pull/62

tl;dr it's a stray question mark causing the pattern `   (` to be matched (whitespace and parenthesis).

**Comment by broffin** [comment]
@jzhu98 Well done, I've glanced over some files and it doesn't appear to break anything. Also fixes the same issue in Sublime.
