### ISSUE TITLE
Weird alignment of line-numbers in the gutter

### ISSUE THREAD

**Issue by olmokramer** [jesseweed/seti-syntax#30]
This image says it all:
![seti-gutter-weird](https://cloud.githubusercontent.com/assets/3612514/5741983/20ddd3ec-9c0f-11e4-85e3-d2217955864d.png)

## Versions

* **Atom:**       0.172.0
* **Atom-Shell:** 0.20.5
* **OS:**         linux 3.18-2.dmz.1-liquorix-amd64
* **Misc**
    * apm  0.119.0
    * npm  1.4.4
    * node 0.10.35
    * python 2.7.8
    * git 2.1.4

**Comment by jesseweed** [comment]
I believe this has been fixed. Feel free to re-open if you're still seeing it.

**Comment by olmokramer** [comment]
I can confirm it works! Thanks :)
