### ISSUE TITLE
Got Deprecated Selectors 

### ISSUE THREAD

**Issue by dinosaurfiles** [jesseweed/seti-syntax#34]
>index.less
>Use the `atom-text-editor` tag instead of the `editor-colors` class.
>Use the `atom-text-editor` tag instead of the `editor` class.
>Use the selector `atom-text-editor[mini]` to select mini-editors.

**Comment by asantos3** [comment]
[There's a open pull request  for that.](https://github.com/jesseweed/seti-syntax/pull/31).

**Comment by dinosaurfiles** [comment]
my bad. closing it now
