### ISSUE TITLE
Line no and line background is not highlighted as shown

### ISSUE THREAD

**Issue by phalvinayak** [jesseweed/seti-syntax#35]
Current line and line are not highlighted as shown
![](https://github.com/jesseweed/seti-ui/raw/master/screenshot.png)

Please refer the screen shot.
![untitled](https://cloud.githubusercontent.com/assets/230028/6024230/a39e4fb0-abef-11e4-865a-679d94afafb6.png)

**Comment by jesseweed** [comment]
Interesting, I'm not seeing this issue. Can you confirm what versions of Atom and Seti you are using?

**Comment by phalvinayak** [comment]
How to check the Version of the Seti UI, Its getting updated...

**Comment by eorroe** [comment]
Put this into your user defined settings:

`"highlight_modified_tabs": true`

**Comment by eorroe** [comment]
I too don't have the icons on the tabs

**Comment by phalvinayak** [comment]
Thanks @eorroe that worked me. Where I'll find all set of configuration list This setting is not listed on the package control page for Seti_UI. Is there any setting to highlight line number as well?

**Comment by eorroe** [comment]
Oh I don't know how he did that. Before I got this theme. I had learned about `highlight_line`. I didn't even realize it till you said, it. Hopefully he sees this conversation and shows us how.

**Comment by phalvinayak** [comment]
Oh, means these settings are already there with sublime then, I've found this link which shows up the few settings, including `highilight_line`. http://sublime-text-unofficial-documentation.readthedocs.org/en/latest/reference/settings.html

**Comment by eorroe** [comment]
Cool thanks. Yet it must be something withing his theme, that we must do. I don't know. Or perhaps it's Only **Atom** that does that not **Sublime**. We're using sublime and he's using **Atom**

**Comment by phalvinayak** [comment]
Oh, I didn't knew that he's using **Atom**, ok one more thing, the preview which he's given on sublime package control page is also not showing the line highlight and icon on the top.

**Comment by eorroe** [comment]
Yea I mentioned that I have that problem too as well. The icons don't show for me on the tabs. We'll have to wait till he replies.

**Comment by jesseweed** [comment]
Hey @eorroe / @phalvinayak it sounds like the issues you're seeing are with the Sublime theme? If that's the case, I recommend creating a ticket over there.

It is actually a whole separate code base maintained by @ctf0 here: https://github.com/ctf0/Seti_ST3

Feel free to re-open if you find the bug in Atom. Thanks!
