### ISSUE TITLE
Deprecation cop still angry

### ISSUE THREAD

**Issue by CaptSaltyJack** [jesseweed/seti-syntax#38]
Using the latest version of everything.

    index.less
    Use the `atom-text-editor` tag instead of the `editor-colors` class.
    Use the `atom-text-editor` tag instead of the `editor` class.
    Use the selector `atom-text-editor[mini]` to select mini-editors.

**Comment by johnantoni** [comment]
Yep, same here

**Comment by learning** [comment]
The same +1

**Comment by johnantoni** [comment]
Looks like this was tackled before https://github.com/jesseweed/seti-syntax/pull/31

**Comment by jesseweed** [comment]
Ah dang, missed that in the last update. I'll get that in next.

**Comment by jesseweed** [comment]
Deprecation errors have been addressed in 0.3.2 update.
