### ISSUE TITLE
ThemePackage.getStylesheetsPath is deprecated.

### ISSUE THREAD

**Issue by FlashxGamer** [jesseweed/seti-syntax#68]
Store package style sheets in the `styles/` directory instead of `stylesheets/` in the `seti-syntax` package
```
ThemePackage.getStylesheetsPath (C:\Users\Sigma\AppData\Local\atom\app-0.189.0\resources\app\src\package.js:448:9)
ThemePackage.getStylesheetPaths (C:\Users\Sigma\AppData\Local\atom\app-0.189.0\resources\app\src\package.js:459:32)
```

**Comment by designsimply** [comment]
I'm using seti-syntax with Atom 0.189.0 on OSX and getting the same deprecation notices.

**Comment by asantos3** [comment]
[There's a open pull request for that.](https://github.com/jesseweed/seti-syntax/pull/66)

**Comment by asantos3** [comment]
Duplicate of #67.
