### ISSUE TITLE
ThemePackage.getStylesheetsPath is deprecated.

### ISSUE THREAD

**Issue by rbonafe** [jesseweed/seti-syntax#84]
Store package style sheets in the `styles/` directory instead of `stylesheets/` in the `seti-syntax` package
```
ThemePackage.getStylesheetsPath (/Applications/Atom.app/Contents/Resources/app/src/package.js:430:9)
ThemePackage.getStylesheetPaths (/Applications/Atom.app/Contents/Resources/app/src/package.js:441:32)
```
ThemePackage.getStylesheetsPath - /Applications/Atom.app/Contents/Resources/app/src/package.js:430:9
<unknown> - /Applications/Atom.app/Contents/Resources/app/src/theme-manager.js:434:35

OS X 10.10.3; Atom v0.190.0

**Comment by asantos3** [comment]
Duplicate of #67, please close this.
